/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dao.ClienteDao;
import dao.CuentaDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.CuentaLogica;
import logica.NacionalidadLogica;
import logica.MovimientoLogica;
import dao.MovimientoDao;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DeadAim
 */
public class JIFraTransfer extends javax.swing.JFrame {

    /**
     * Creates new form JIFraTransfer
     */
    public JIFraTransfer() {
        initComponents();
        jLblCuenta.setVisible(false);
        jCboIdCuentaD.setVisible(false);
        llenarCboCuenta();
        llenarTMovimiento();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTFMonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCboIdCuenta = new javax.swing.JComboBox<>();
        jCboIdCuentaD = new javax.swing.JComboBox<>();
        jLblCuenta = new javax.swing.JLabel();
        jRBRetiro = new javax.swing.JRadioButton();
        jRBDeposito = new javax.swing.JRadioButton();
        jRBTransferencia = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMovimiento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setText("IdCuenta");

        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel2.setText("Monto");

        jLblCuenta.setText("Cuenta Destino");

        buttonGroup1.add(jRBRetiro);
        jRBRetiro.setText("Retiro");

        buttonGroup1.add(jRBDeposito);
        jRBDeposito.setText("Deposito");

        buttonGroup1.add(jRBTransferencia);
        jRBTransferencia.setText("Transferencia");
        jRBTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTransferenciaActionPerformed(evt);
            }
        });

        jTblMovimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdMovimiento", "IdTipoMovimiento", "Fecha_Movimiento", "IdCuentaT", "IdCuentaR", "Monto"
            }
        ));
        jScrollPane1.setViewportView(jTblMovimiento);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel4.setText("MOVIMIENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jCboIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBRetiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBDeposito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBTransferencia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboIdCuentaD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(268, 268, 268))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jCboIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBRetiro)
                            .addComponent(jRBDeposito)
                            .addComponent(jRBTransferencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboIdCuentaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblCuenta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:

        try {
            CuentaDao dao = new CuentaDao();
            CuentaLogica c1 = new CuentaLogica();
            MovimientoLogica m1 = new MovimientoLogica();
            MovimientoDao daom = new MovimientoDao();
            
            c1.setIdCuenta(Integer.parseInt(jCboIdCuenta.getSelectedItem().toString()));
            if (jRBDeposito.isSelected()) {
                dao.depositarSaldo(c1, Double.parseDouble(jTFMonto.getText()));
                m1.setIdCuentaT(c1.getIdCuenta());
                m1.setIdTipoMovimiento(2);
                m1.setMonto(Double.parseDouble(jTFMonto.getText()));
                daom.insertarMovimiento(m1);
                
            }
            if (jRBRetiro.isSelected()) {
                dao.retirarSaldo(c1, Double.parseDouble(jTFMonto.getText()));
                m1.setIdCuentaT(c1.getIdCuenta());
                m1.setIdTipoMovimiento(1);
                m1.setMonto(Double.parseDouble(jTFMonto.getText()));
                daom.insertarMovimiento(m1);
            }
            if (jRBTransferencia.isSelected()) {
                CuentaLogica c2 = new CuentaLogica();
                c2.setIdCuenta(Integer.parseInt(jCboIdCuentaD.getSelectedItem().toString()));
                dao.retirarSaldo(c1, Double.parseDouble(jTFMonto.getText()));
                dao.depositarSaldo(c2, Double.parseDouble(jTFMonto.getText()));
                m1.setIdCuentaT(c1.getIdCuenta());
                m1.setIdCuentaR(c2.getIdCuenta());
                m1.setIdTipoMovimiento(3);
                m1.setMonto(Double.parseDouble(jTFMonto.getText()));
                daom.insertarMovimiento(m1);
            }
            llenarTMovimiento();
        } catch (SQLException ex) {
            
        }

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jRBTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTransferenciaActionPerformed
        // TODO add your handling code here:
        if(jLblCuenta.isVisible()){
            jLblCuenta.setVisible(false);
            jCboIdCuentaD.setVisible(false);
        }else{
            jLblCuenta.setVisible(true);
            jCboIdCuentaD.setVisible(true);
        }
    }//GEN-LAST:event_jRBTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JIFraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JIFraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JIFraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JIFraTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JIFraTransfer().setVisible(true);
            }
        });
    }
    
    private void llenarCboCuenta() {
        try {
            CuentaDao dao = new CuentaDao();
            jCboIdCuenta.removeAllItems();
            
            List<CuentaLogica> miComboCuenta;
            
            miComboCuenta = dao.getLista();
            
            for (int i = 0; i < miComboCuenta.size(); i++) {
                
                jCboIdCuenta.addItem(String.valueOf(miComboCuenta.get(i).getIdCuenta()));
                jCboIdCuentaD.addItem(String.valueOf(miComboCuenta.get(i).getIdCuenta()));
                
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    private void llenarTMovimiento() {
        try {
            limpiarTabla();
            
            MovimientoDao dao = new MovimientoDao();
            List<MovimientoLogica> miLista = dao.getLista();
            
            DefaultTableModel temp = (DefaultTableModel) this.jTblMovimiento.getModel();
            
            for (MovimientoLogica m1 : miLista) {
                
                Object[] fila = new Object[6];
                
                fila[0] = m1.getIdMovimiento();
                fila[1] = m1.getIdTipoMovimiento();
                fila[2] = m1.getFecha_Movimiento();
                fila[3] = m1.getIdCuentaT();
                fila[4] = m1.getIdCuentaR();
                fila[5] = m1.getMonto();
                temp.addRow(fila);
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    private void limpiarTabla() {
        
        DefaultTableModel temp = (DefaultTableModel) this.jTblMovimiento.getModel(); //

        // Limpiar los datos de la tabla.
        while (temp.getRowCount() > 0) {
            temp.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JComboBox<String> jCboIdCuenta;
    private javax.swing.JComboBox<String> jCboIdCuentaD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBDeposito;
    private javax.swing.JRadioButton jRBRetiro;
    private javax.swing.JRadioButton jRBTransferencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFMonto;
    private javax.swing.JTable jTblMovimiento;
    // End of variables declaration//GEN-END:variables
}
