/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;


import dao.ClienteDao;
import dao.CuentaDao;
import dao.MovimientoDao;
import dao.TipoCuentaDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.ClienteLogica;
import logica.CuentaLogica;
import logica.MovimientoLogica;
import logica.NacionalidadLogica;
import logica.TipoCuentaLogica;

/**
 *
 * @author griselda
 */
public class JIFraCuenta
        extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFraCuenta
     */
    public JIFraCuenta() {
        initComponents();
        llenarCC();
        llenarCTipoC();
        llenarCMov();
        habilitarBotones(true,false,false,false,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFIdCuenta = new javax.swing.JTextField();
        jCboCliente = new javax.swing.JComboBox<>();
        jCboTipoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCuenta = new javax.swing.JTable();
        jBtnNuevo = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jFTFFechaC = new javax.swing.JFormattedTextField();
        jFTFSaldo = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jCboMovimiento = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTFMonto = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("GESTIONAR CUENTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IdCuenta");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente Asociado");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo  Cuenta");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo Inicial");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Creacion");

        jTblCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Cuenta", "Cliente", "Tipo Cuenta", "Fecha de Creacion", "Tipo Movimiento", "Saldo Anterior", "Saldo Movimiento", "Saldo Actual"
            }
        ));
        jTblCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTblCuentaMousePressed(evt);
            }
        });
        jTblCuenta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTblCuentaComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTblCuenta);

        jBtnNuevo.setIcon(new javax.swing.ImageIcon("/Users/griselda/Documents/GitHub/INGBankPoo/INGBank/src/imagenes/new.png")); // NOI18N
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBtnGuardar.setIcon(new javax.swing.ImageIcon("/Users/griselda/Documents/GitHub/INGBankPoo/INGBank/src/imagenes/save.png")); // NOI18N
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnModificar.setIcon(new javax.swing.ImageIcon("/Users/griselda/Documents/GitHub/INGBankPoo/INGBank/src/imagenes/edit.png")); // NOI18N

        jBtnEliminar.setIcon(new javax.swing.ImageIcon("/Users/griselda/Documents/GitHub/INGBankPoo/INGBank/src/imagenes/delete.png")); // NOI18N

        try {
            jFTFFechaC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFTFSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo Movimiento");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jBtnNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnEliminar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCboTipoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFIdCuenta))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFTFSaldo)
                                        .addComponent(jFTFFechaC, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                        .addComponent(jCboMovimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jTFIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFFechaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jFTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCboTipoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jCboMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnNuevo)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnModificar)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void limpiar() {
       jTFIdCuenta.setText("");
       jFTFFechaC.setText("");
       jFTFSaldo.setText("");   
    }
    
    private void guardarCuenta(){
        
        CuentaLogica c1 = new CuentaLogica();
        
        c1.setIdCuenta(Integer.parseInt(this.jTFIdCuenta.getText()));
        c1.setIdCliente(this.jCboCliente.getSelectedIndex() + 1);
        c1.setIdTipoCuenta(this.jCboTipoc.getSelectedIndex() + 1);
        c1.setSaldo(Double.parseDouble(this.jFTFSaldo.getText()));
        c1.setFecha_de_Creacion(this.jFTFFechaC.getText());
        c1.setIdTipoCuenta(this.jCboTipoc.getSelectedIndex() + 1);
     
         
             
        try {
            CuentaDao dao = new CuentaDao();
            dao.insertarCuenta(c1);
            JOptionPane.showMessageDialog(null, "Registro almacenado satisfactoriamente.");
            limpiar();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al almacenar la Cuenta." + e);
        }
    }

 private void llenarTCuenta() throws SQLException{
    //limpiarTabla();
        
        CuentaDao dao = new CuentaDao();
        List<CuentaLogica> miLista = dao.getLista();
        
        DefaultTableModel temp = (DefaultTableModel) this.jTblCuenta.getModel(); 
        
        for(CuentaLogica c1:miLista){
          
            Object[] fila = new Object[5];
           
            
                fila[0] = c1.getIdCuenta();
                fila[1] = c1.getIdCliente();
                fila[2] = c1.getIdTipoCuenta();
                fila[3] = c1.getSaldo();
                fila[4] = c1.getFecha_de_Creacion();
                temp.addRow(fila);
               
        } 
}
private void llenarCMov(){
       try{
        MovimientoDao dao = new MovimientoDao();   
        jCboMovimiento.removeAllItems();

        List<MovimientoLogica> miComboMov;

        miComboMov = dao.getComboMov();

        for(int i=0; i<miComboMov.size();i++){

            jCboMovimiento.addItem(miComboMov.get(i).getMovimiento());
        }
        
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }
    
}
 private void llenarCC(){
       try{
        TipoCuentaDao dao = new TipoCuentaDao();   
        jCboCliente.removeAllItems();

        List<ClienteLogica> miComboCliente;

        miComboCliente = dao.getComboCliente();

        for(int i=0; i<miComboCliente.size();i++){

            jCboCliente.addItem(miComboCliente.get(i).getNombres());
        }
        
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }
    
}
private void llenarCTipoC(){
         try{
        TipoCuentaDao dao = new TipoCuentaDao();   
        jCboTipoc.removeAllItems();

        List<TipoCuentaLogica> miComboTipoCuenta;

        miComboTipoCuenta = dao.getComboTipoC();

        for(int i=0; i<miComboTipoCuenta.size();i++){

            jCboTipoc.addItem(miComboTipoCuenta.get(i).getTipoCuenta());
        }
        
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }
} 
    private void jTblCuentaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTblCuentaComponentShown
          try {
            llenarTCuenta();
          DefaultTableModel temp = (DefaultTableModel) this.jTblCuenta.getModel();
           temp.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(JIFraCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTblCuentaComponentShown
        private void investigarCorrelativo() throws SQLException{
        CuentaDao dao = new CuentaDao();
        CuentaLogica c1 = new CuentaLogica();
        c1.setIdCuenta(dao.autoIncrementar());
        jTFIdCuenta.setText(String.valueOf(c1.getIdCuenta()));
        
    }
    private boolean verificarTextField(){
        boolean estado;
        
        if(jTFIdCuenta.getText().isEmpty()  || jFTFFechaC.getText().isEmpty() || jFTFSaldo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese los campos vacios");
            estado = false;    
        }else{
            estado = true;
        }
        return estado;
    }
         private void habilitarBotones(boolean nuevo, boolean guardar, boolean modificar, boolean eliminar, boolean textField){
        jTFIdCuenta.setEnabled(nuevo);
        jBtnGuardar.setEnabled(guardar);
        jBtnModificar.setEnabled(modificar);
        jBtnEliminar.setEnabled(eliminar);
        jTFIdCuenta.setEditable(textField);
        jCboCliente.setEditable(textField);
        jCboTipoc.setEditable(textField);
        jFTFFechaC.setEditable(textField);
        jFTFSaldo.setEditable(textField);
        jTFMonto.setEditable(textField);
        
    }  
       private void lineaSeleccionada() {
        if (this.jTblCuenta.getSelectedRow() != -1) {
            //Habilito los controles para que se pueda hacer una accion.
            if (this.jTblCuenta.isEnabled() == true) {
                this.jTFIdCuenta.setText(String.valueOf(this.jTblCuenta.getValueAt(jTblCuenta.getSelectedRow(), 0)));
                this.jFTFSaldo.setText(String.valueOf(this.jTblCuenta.getValueAt(jTblCuenta.getSelectedRow(), 3)));
                this.jFTFFechaC.setText(String.valueOf(this.jTblCuenta.getValueAt(jTblCuenta.getSelectedRow(), 4)));
                
            }
        } else {
            limpiar();
        }
    }
     
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
            if(verificarTextField()==true){
            guardarCuenta();
            habilitarBotones(true, false, false, false, false); 
            try {
                llenarTCuenta();
            } catch (SQLException ex) {
                Logger.getLogger(JIFraCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
          limpiar();
        habilitarBotones(false, true, false, false, true);
       
        try {
            investigarCorrelativo();
        } catch (SQLException ex) {
            Logger.getLogger(JIFraCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
             habilitarBotones(false, true, false, false, true);
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jTblCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblCuentaMousePressed
       lineaSeleccionada();
        habilitarBotones(false, false, true, true, true);
    }//GEN-LAST:event_jTblCuentaMousePressed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox<String> jCboCliente;
    private javax.swing.JComboBox<String> jCboMovimiento;
    private javax.swing.JComboBox<String> jCboTipoc;
    private javax.swing.JFormattedTextField jFTFFechaC;
    private javax.swing.JFormattedTextField jFTFSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFIdCuenta;
    private javax.swing.JTextField jTFMonto;
    private javax.swing.JTable jTblCuenta;
    // End of variables declaration//GEN-END:variables
}
